on: 
  push:
   paths:
     - './desafio5/*'
  pull_request:
   paths:
     - './desafio5/*'
jobs:
  tests:
    name: run tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
        working-directory: ./desafio5/app-fullcycle4-d5
      - run: npm run test
        working-directory: ./desafio5/app-fullcycle4-d5
      - run: npm run test:e2e
        working-directory: ./desafio5/app-fullcycle4-d5
      - run: test coverage
        working-directory: ./desafio5/app-fullcycle4-d5
